import tkinter as tk
from tkinter import messagebox
def submit_form():
    name = name_entry.get()
    email = email_entry.get()
    phone = phone_entry.get()
    password = password_entry.get()
    gender = gender_var.get()
    if name and email and phone and password and gender:
        messagebox.showinfo("Success", "Registration Successful!")
        print("----- Registration Details -----")
        print("Name:", name)
        print("Email:", email)
        print("Phone:", phone)
        print("Gender:", gender)
    else:
        messagebox.showwarning("Error", "All fields are required!")
root = tk.Tk()
root.title("Registration Form")
root.geometry("400x350")
root.resizable(False, False)
tk.Label(root, text="Registration Form", font=("Arial", 16, "bold")).grid(row=0, column=0, columnspan=2, pady=10)
tk.Label(root, text="Full Name:").grid(row=1, column=0, padx=10, pady=5, sticky="w")
name_entry = tk.Entry(root, width=25)
name_entry.grid(row=1, column=1, padx=10, pady=5)
tk.Label(root, text="Email Address:").grid(row=2, column=0, padx=10, pady=5, sticky="w")
email_entry = tk.Entry(root, width=25)
email_entry.grid(row=2, column=1, padx=10, pady=5)
tk.Label(root, text="Phone Number:").grid(row=3, column=0, padx=10, pady=5, sticky="w")
phone_entry = tk.Entry(root, width=25)
phone_entry.grid(row=3, column=1, padx=10, pady=5)
tk.Label(root, text="Password:").grid(row=4, column=0, padx=10, pady=5, sticky="w")
password_entry = tk.Entry(root, width=25, show="*")
password_entry.grid(row=4, column=1, padx=10, pady=5)
tk.Label(root, text="Gender:").grid(row=5, column=0, padx=10, pady=5, sticky="w")
gender_var = tk.StringVar()
tk.Radiobutton(root, text="Male", variable=gender_var, value="Male").grid(row=5, column=1, sticky="w")
tk.Radiobutton(root, text="Female", variable=gender_var, value="Female").grid(row=6, column=1, sticky="w")
tk.Button(root, text="Register", command=submit_form, bg="blue", fg="white").grid(row=7, column=0, columnspan=2, pady=15)
root.mainloop()