import tkinter as tk
from tkinter import messagebox
def submit():
    name = entry_name.get()
    email = entry_email.get()
    phone = entry_phone.get()
    password = entry_password.get()
    gender = gender_var.get()
    if name == "" or email == "" or phone == "" or password == "" or gender == "":
        messagebox.showwarning("Warning", "All fields are required!")
    else:
        messagebox.showinfo("Success", "Registration Successful!")
        print("Name:", name)
        print("Email:", email)
        print("Phone:", phone)
        print("Gender:", gender)
root = tk.Tk()
root.title("Registration Form")
root.geometry("400x400")
tk.Label(root, text="Name").pack()
entry_name = tk.Entry(root)
entry_name.pack()
tk.Label(root, text="Email").pack()
entry_email = tk.Entry(root)
entry_email.pack()
tk.Label(root, text="Phone").pack()
entry_phone = tk.Entry(root)
entry_phone.pack()
tk.Label(root, text="Password").pack()
entry_password = tk.Entry(root, show="*")
entry_password.pack()
tk.Label(root, text="Gender").pack()
gender_var = tk.StringVar()
tk.Radiobutton(root, text="Male", variable=gender_var, value="Male").pack()
tk.Radiobutton(root, text="Female", variable=gender_var, value="Female").pack()
tk.Button(root, text="Submit", command=submit).pack(pady=10)
root.mainloop()